version: "3"

services:
    sfadxinfo:
        build: sfadxinfo
        image: sfadxinfo
        #restart: always
        restart: "no"
        environment:
            TZ: ${TZ}
            USERNAME: ${USERNAME}
            CLIENTID: ${CLIENTID}
            JWTKEYFILE: ${JWTKEYFILE}
        logging:
            driver: ${LOGDRIVER}

    apatchphp_webapp:
        image: apatchphp_webapp
        build: apatchphp_webapp
        restart: "always"
        depends_on:
            - radisds
        ports:
            - "80"
        environment:
            TZ: ${TZ}
        logging:
            driver: ${LOGDRIVER}
        volumes:
            - ./apatchphp_webapp/contents/:/var/www/html/

    radisds:
        image: redisds
        build: redisds
        restart: "always"
        ports:
            - "6379:6379"
        # command: redis-server --appendonly yes
        logging:
            driver: ${LOGDRIVER}
        #volumes:
        #    - /radis_data:/data

    react_app:
        image: react_app
        build:
            context: react_app
            dockerfile: Dockerfile-pro
        ports:
            - "80:80"
        restart: always
        environment:
            TZ: ${TZ}
        logging:
            driver: ${LOGDRIVER}
