#FROM node:latest
FROM node:14-alpine
LABEL maintaner='y-yoshimoto'
ENV APPNAME sfdx-api-graph

RUN mkdir -p /$APPNAME/src && mkdir -p /$APPNAME/public
WORKDIR /$APPNAME

COPY ./package.json /$APPNAME/package.json
RUN yarn install 

# Remove Sample
COPY ./src /sfdx-api-graph/src
COPY ./public /sfdx-api-graph/public

EXPOSE 3000 

ENTRYPOINT ["tail", "-f", "/dev/null"]
#ENTRYPOINT ["yarn", "start"]